name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERUSER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}  
      run: |
        docker login -u $DOCKERUSER -p $DOCKERPASSWORD
    - name: docker build iva-slack-auto-report
      run: |
        docker build -t tribuwana/grafana-report-mailer:latest .
    - name: docker push
      run: |
        docker push  tribuwana/grafana-report-mailer:latest
